import type { Pattern } from "@/lib/game-of-life";

export const GAME_NAME = "Conway's Game of Life";
export const SIMULATOR_NAME = "Life Simulator";
export const GRID_SIZE_DEFAULTS = [
  { label: "Small", rows: 30, cols: 40, description: "30 × 40" },
  { label: "Medium", rows: 50, cols: 70, description: "50 × 70" },
  { label: "Large", rows: 70, cols: 100, description: "70 × 100" },
  { label: "Extra Large", rows: 100, cols: 140, description: "100 × 140" },
];

export const PATTERNS: Pattern[] = [
  {
    id: "glider",
    name: "Glider",
    description: "Classic spaceship that moves diagonally",
    category: "spaceship",
    cells: [
      [0, 1],
      [1, 2],
      [2, 0],
      [2, 1],
      [2, 2],
    ],
  },
  {
    id: "blinker",
    name: "Blinker",
    description: "Period 2 oscillator",
    category: "oscillator",
    cells: [
      [0, 0],
      [0, 1],
      [0, 2],
    ],
  },
  {
    id: "beacon",
    name: "Beacon",
    description: "Period 2 oscillator",
    category: "oscillator",
    cells: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 1],
      [2, 2],
      [2, 3],
      [3, 2],
      [3, 3],
    ],
  },
  {
    id: "pulsar",
    name: "Pulsar",
    description: "Period 3 oscillator",
    category: "oscillator",
    cells: [
      [0, 2],
      [0, 3],
      [0, 4],
      [0, 8],
      [0, 9],
      [0, 10],
      [2, 0],
      [2, 5],
      [2, 7],
      [2, 12],
      [3, 0],
      [3, 5],
      [3, 7],
      [3, 12],
      [4, 0],
      [4, 5],
      [4, 7],
      [4, 12],
      [5, 2],
      [5, 3],
      [5, 4],
      [5, 8],
      [5, 9],
      [5, 10],
      [7, 2],
      [7, 3],
      [7, 4],
      [7, 8],
      [7, 9],
      [7, 10],
      [8, 0],
      [8, 5],
      [8, 7],
      [8, 12],
      [9, 0],
      [9, 5],
      [9, 7],
      [9, 12],
      [10, 0],
      [10, 5],
      [10, 7],
      [10, 12],
      [12, 2],
      [12, 3],
      [12, 4],
      [12, 8],
      [12, 9],
      [12, 10],
    ],
  },
  {
    id: "block",
    name: "Block",
    description: "Simple still life",
    category: "still",
    cells: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 1],
    ],
  },
  {
    id: "beehive",
    name: "Beehive",
    description: "Common still life",
    category: "still",
    cells: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 3],
      [2, 1],
      [2, 2],
    ],
  },
  {
    id: "loaf",
    name: "Loaf",
    description: "Still life pattern",
    category: "still",
    cells: [
      [0, 1],
      [0, 2],
      [1, 0],
      [1, 3],
      [2, 1],
      [2, 3],
      [3, 2],
    ],
  },
  {
    id: "lwss",
    name: "Lightweight Spaceship",
    description: "Fast moving spaceship",
    category: "spaceship",
    cells: [
      [0, 1],
      [0, 4],
      [1, 0],
      [2, 0],
      [2, 4],
      [3, 0],
      [3, 1],
      [3, 2],
      [3, 3],
    ],
  },
  {
    id: "pentadecathlon",
    name: "Pentadecathlon",
    description: "Period 15 oscillator",
    category: "oscillator",
    cells: [
      [0, 1],
      [1, 1],
      [2, 0],
      [2, 2],
      [3, 1],
      [4, 1],
      [5, 1],
      [6, 1],
      [7, 0],
      [7, 2],
      [8, 1],
      [9, 1],
    ],
  },
  {
    id: "gosper-gun",
    name: "Gosper Glider Gun",
    description: "First known gun, emits gliders",
    category: "spaceship",
    cells: [
      [0, 24],
      [1, 22],
      [1, 24],
      [2, 12],
      [2, 13],
      [2, 20],
      [2, 21],
      [2, 34],
      [2, 35],
      [3, 11],
      [3, 15],
      [3, 20],
      [3, 21],
      [3, 34],
      [3, 35],
      [4, 0],
      [4, 1],
      [4, 10],
      [4, 16],
      [4, 20],
      [4, 21],
      [5, 0],
      [5, 1],
      [5, 10],
      [5, 14],
      [5, 16],
      [5, 17],
      [5, 22],
      [5, 24],
      [6, 10],
      [6, 16],
      [6, 24],
      [7, 11],
      [7, 15],
      [8, 12],
      [8, 13],
    ],
  },
];
